@startuml

skinparam linetype splines

node "SDL Adapter" {
  interface "TCP Transport Adapter" as TCP 
  interface "BT Transport Adapter" as BT 
  interface "USB Transport Adapter" as USB 
  [Transport Manager] -- TCP
  [Transport Manager] -- BT
  [Transport Manager] -- USB
  [SDLInit]
  [HMI Message Brocker]
} 


node "SDL BusinessLogic" {
  [Application Manager]
  [RPC Service]
  [Media Manager]
  [Policy Manager]
  [Protocol Handler]
} 

[Transport Manager] -up- [Protocol Handler]
[HMI Message Brocker] -- [RPC Service]
[SDLInit] -up- [Protocol Handler]
[SDLInit] -up- [Application Manager]
[SDLInit] -up- [Policy Manager]
[SDLInit] -up-  [Media Manager]

@enduml
